### ISSUE TITLE
dfm add ~/.emacs.d does not add to tracked files.

### ISSUE THREAD

**Issue by cbusenbu** [chasinglogic/dfm#33]
Traceback (most recent call last):
  File "/usr/local/bin/dfm", line 11, in <module>
    sys.exit(dfm())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dfm/cli.py", line 182, in add
    add_file(f, profile)
  File "/usr/local/lib/python3.6/site-packages/dfm/lib/__init__.py", line 147, in add_file
    link_file(new_path, bytes(old_file), force=True)
  File "/usr/local/lib/python3.6/site-packages/dfm/lib/__init__.py", line 96, in link_file
    if CONFIG['verbose']:
KeyError: 'verbose'

It does end up linking the file, but it doesn't look like it adds it to git tracking. I tried to commit afterwards, and my .emacs.d was untracked.

**Comment by chasinglogic** [comment]
The stack trace was caused by a completely unrelated error which caused the program to crash before it got to adding the file in git, I've fixed this bug and tested dfm add on my local box and it's working, pushing a fix soon
